FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=mutillidae
ENV MYSQL_DATABASE=mutillidae
ENV MYSQL_USER=mutillidae
ENV MYSQL_PASSWORD=mutillidae

RUN mkdir -p /docker-entrypoint-initdb.d

EXPOSE 3306

CMD ["mysqld"]

